// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_web_app;

#nullable disable

namespace mvc_web_app.Migrations
{
    [DbContext(typeof(MvcWebAppContext))]
    [Migration("20220117223909_database")]
    partial class database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("mvc_web_app.Models.Inquilino", b =>
                {
                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sexo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("nome");

                    b.ToTable("Inquilino");
                });

            modelBuilder.Entity("mvc_web_app.Models.Unidade", b =>
                {
                    b.Property<string>("indentificacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("condominio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("proprietario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("indentificacao");

                    b.HasIndex("proprietario");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("mvc_web_app.Models.Unidade", b =>
                {
                    b.HasOne("mvc_web_app.Models.Inquilino", "inquilino")
                        .WithMany("unidades")
                        .HasForeignKey("proprietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inquilino");
                });

            modelBuilder.Entity("mvc_web_app.Models.Inquilino", b =>
                {
                    b.Navigation("unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
