// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc_web_app;

#nullable disable

namespace mvc_web_app.Migrations
{
    [DbContext(typeof(MvcWebAppContext))]
    [Migration("20220123221244_ModelToDatabase")]
    partial class ModelToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("mvc_web_app.Models.DespesaDaUnidade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("statusPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tipoDespesa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("unidadeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("valor")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("vencimento_fatura")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("DespesasDasUnidades");
                });

            modelBuilder.Entity("mvc_web_app.Models.Inquilino", b =>
                {
                    b.Property<string>("cpfCnpj")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("cpfCnpj");

                    b.ToTable("Inquilino");
                });

            modelBuilder.Entity("mvc_web_app.Models.Unidade", b =>
                {
                    b.Property<string>("indentificacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("condominio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("proprietario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("indentificacao");

                    b.ToTable("Unidade");
                });
#pragma warning restore 612, 618
        }
    }
}
